Update single-mount

diff --git a/Linux/ShellScript/single-mount b/Linux/ShellScript/single-mount
--- a/Linux/ShellScript/single-mount
+++ b/Linux/ShellScript/single-mount
@@ -1,5 +1,5 @@
 #!/bin/bash
-# PowerBy e.tuchs
+# PowerBy xwl
 # 2016.05.10 Ver 1.1.2
 objname=`echo $1 | awk -F "/" '{print $NF}' | awk -F "." '{print $1}'`
 base=/mnt
@@ -43,8 +43,23 @@ mount -o "mode=0620,gid=5" -t devpts devpts $aufsdir/dev/pts
 mount -t tmpfs tmpfs $aufsdir/dev/shm
 mount -t tmpfs tmpfs $aufsdir/tmp
 mount -t tmpfs tmpfs $aufsdir/root
-chmod 755 $aufsdir/run/dbus
-mkdir -p $aufsdir/run/dbus/system_bus_socket
+if [ -f $aufsdir/etc/bashrc ]; then
+    bashfile=$aufsdir/etc/bashrc
+    op_status=1
+elif [ -f $aufsdir/etc/bash.bashrc ]; then
+    bashfile=$aufsdir/etc/bash.bashrc
+    op_status=1
+else
+    echo "Bash File Not found"
+    op_status=0
+fi
+if [ $op_status -eq 1 ]; then
+    echo $bashfile
+    psstr="export PS1='[\u@Docker:$objname:\h \W]\$'"
+    grep -q 'export PS1=' $bashfile && sed -i "s/^export PS1=.*/$psstr/" $bashfile || echo $psstr >> $bashfile
+fi
+chmod 755 $aufsdir/var/run/dbus
+mkdir -p $aufsdir/var/run/dbus/system_bus_socket
 if [ ! -e "$aufsdir/dev/tty0" ]; then
 	ln -s /dev/null $aufsdir/dev/tty0
 	[ $? -eq 0 ] && echo "done1" || echo "fail1"
@@ -54,7 +69,7 @@ fi
 [ -d "$(grep -c " $aufsdir/dev/pts " /proc/mounts)" ] || mkdir -p $aufsdir/dev/pts
 chroot $aufsdir sh -c "dbus-uuidgen > /etc/machine-id"
 [ $? -eq 0 ] && echo "done2" || echo "fail2"
-[ -e "$aufsdir/run/dbus/pid" ] && rm $aufsdir/run/dbus/pid
+[ -e "$aufsdir/var/run/dbus/pid" ] && rm $aufsdir/var/run/dbus/pid
 chroot $aufsdir dbus-daemon --system --fork
 while true; do
     read -p "Do you need chroot to: $aufsdir now? Y/N  " yn
@@ -63,4 +78,3 @@ while true; do
         [Nn]* ) echo "Please use: sudo chroot $aufsdir to entry new env if you want!";break;;
     esac
 done
-
